trigger:
- master

pool:
 vmImage: 'ubuntu-latest'
 
stages:
- stage: Build
  variables:
   environment: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo $(environment) FirstJob 1    
  - job: SecondJob
    steps:
    - bash: echo Build SecondJob 2
    - bash: echo $(PipelineLevelVariable)
- stage: DevDeploy
  variables:
   environment: Dev   
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo $(environment)DeployJob
- stage: QADeploy
  variables:
   environment: QA
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo $(environment)DeployJob
- stage: ProdDeploy
  variables:
   environment: Prod
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo $(environment)DeployJob