trigger:
- master

pool:
 vmImage: 'ubuntu-latest'

stages:
- stage: DevDeploy
  jobs:
  - deployment: DevDeployJob
    environment: Dev
    strategy:
     runOnce:
      deploy:
       steps:
       - script: echo deploy to $(environment)
- stage: QADeploy
  jobs:
  - deployment: QADeployJob
    environment: QA
    strategy:
     runOnce:
      deploy:
       steps:
       - script: echo deploy to $(environment)